-- Seed: un grupo de keywords por subcategoría (~60 filas, ~1226 keywords).
-- Requiere migración 0032 (modelo por grupo). Idempotente: no pisa filas ya existentes.

with seed(lookup_slug, keywords) as (
  values
  ('automovil-coches', array['neumatico', 'llanta', 'aceite motor', 'limpiaparabrisas', 'alfombrilla coche', 'cargador coche', 'compresor coche', 'alfombrillas coche', 'soporte movil coche', 'cargador bateria coche', 'obd2', 'fundas asientos coche', 'rascador hielo', 'organizador maletero', 'gato hidraulico', 'liquido frenos', 'arrancador coches', 'bombillas coche h7', 'liquido refrigerante', 'volante coche', 'funda volante', 'parasol coche', 'cadenas nieve', 'gato coche', 'espejo angulo muerto']::text[]),
  ('automovil-motos', array['casco moto', 'guantes moto', 'chaqueta moto', 'candado disco moto', 'intermitentes moto', 'funda moto', 'maleta baul moto', 'antirrobo moto', 'pantalla casco', 'intercomunicador moto', 'riñonera moto', 'botas moto', 'pantalones moto', 'piton moto', 'cargador bateria moto', 'tapa colin']::text[]),
  ('automovil-seguridad', array['silla coche', 'portabebes', 'dash cam', 'alarma coche', 'camara dashcam', 'localizador gps coche', 'cámara trasera coche', 'sensor aparcamiento', 'baston volante', 'bloqueo freno mano', 'camara salpicadero', 'alarma moto', 'tracker gps']::text[]),
  ('bebe-bebes', array['cochecito', 'silla de paseo', 'biberon', 'chupete', 'pañales', 'panales', 'pañal', 'carrito bebe', 'trona', 'cuna', 'silla coche', 'neceser bebe', 'mochila porteo', 'esterilizador', 'vigilabebés', 'canastilla', 'badana', 'bodies bebe', 'taza aprendizaje', 'hamaca bebe', 'parque bebe', 'chupetero', 'mordedor', 'orinal', 'reductor wc', 'bolsa carro bebe', 'cambiador portatil', 'muselinas', 'saco dormir bebe', 'termometro baño', 'aspirador nasal', 'canguro bebe']::text[]),
  ('bebe-ninos', array['niño', 'nina', 'infantil', 'colegio', 'ropa niño', 'ropa niña', 'zapato infantil', 'chandal niño', 'vestido niña', 'abrigo infantil', 'pijama niño', 'mochila escolar infantil', 'camisa niño', 'pantalon infantil', 'falda niña', 'sudadera niño', 'conjunto infantil', 'babi colegio', 'impermeable niño', 'bañador infantil']::text[]),
  ('belleza-cuidado-personal', array['champu', 'gel de ducha', 'desodorante', 'afeitadora', 'secador pelo', 'depiladora', 'cepillo electrico', 'plancha pelo', 'recortadora barba', 'irrigador dental', 'mascarilla pelo', 'champú', 'gel baño', 'cepillo dental', 'exfoliante corporal', 'crema corporal', 'cuchillas afeitar', 'espuma afeitar', 'ondulador pelo', 'moldeador cabello', 'cepillo alisador', 'recortadora pelo', 'hilo dental', 'enjuague bucal', 'gel conductor', 'crema depilatoria', 'manicura']::text[]),
  ('belleza-general', array['crema facial', 'serum facial', 'suero facial', 'maquillaje', 'labial', 'rimel', 'protector solar', 'contorno de ojos', 'acido hialuronico', 'mascara de pestañas', 'base maquillaje', 'paleta sombras', 'corrector ojeras', 'colorete', 'esmalte uñas', 'sérum facial', 'crema antiarrugas', 'iluminador', 'fijador maquillaje', 'lapiz labios', 'delineador ojos', 'polvos sol', 'brochas maquillaje', 'desmaquillante', 'agua micelar', 'exfoliante facial', 'mascarilla facial', 'crema hidratante cara', 'bb cream', 'cc cream', 'sombra ojos', 'primer']::text[]),
  ('belleza-perfumes', array['perfume', 'eau de toilette', 'colonia', 'eau de parfum', 'fragancia', 'estuche regalo perfume', 'splash corporal', 'agua de colonia', 'extracto perfume', 'perfume hombre', 'perfume mujer', 'perfume unisex', 'tester perfume', 'miniaturas perfume']::text[]),
  ('belleza-salud', array['vitamina', 'suplemento', 'termometro', 'tensiometro', 'proteina', 'whey', 'whey isolate', 'isolate cfm', 'cfm', 'creatina', 'bcaa', 'aminoacidos', 'preentreno', 'pre-entreno', 'ganador de peso', 'mass gainer', 'colageno', 'omega 3', 'magnesio', 'multivitamin', 'proteina aislada', 'suero de leche', 'tensiómetro', 'mascarilla', 'pulsioximetro', 'oximetro', 'glucometro', 'faja ortopedica', 'coderas', 'rodillera', 'vitaminas', 'pastillero', 'bastón ortopédico', 'muletas', 'cabestrillo', 'termometro infrarrojos', 'test antígenos', 'tiritas', 'gasas esteriles', 'alcohol sanitario', 'agua oxigenada', 'cojin antiescaras', 'musletera', 'tobillera', 'muñequera ortopedica']::text[]),
  ('deportes-aire-libre', array['senderismo', 'montaña', 'baston trekking', 'mochila senderismo', 'bastones trekking', 'linterna frontal', 'saco dormir', 'cantimplora', 'brújula', 'prismáticos', 'gafas sol deportivas', 'chaqueta softshell', 'pantalones montaña', 'botas senderismo', 'poncho lluvia', 'filtro agua portatil', 'reloj gps outdoor', 'hamaca camping', 'navaja multiusos']::text[]),
  ('deportes-camping', array['tienda campaña', 'saco dormir', 'mochila trekking', 'colchón hichable', 'nevera portatil', 'mueble cocina camping', 'silla plegable camping', 'mesa camping', 'ducha portatil', 'saco de dormir momia', 'inflador colchon', 'estufa portatil gas', 'linterna camping', 'vajilla camping', 'toldo impermeable', 'piquetas tienda', 'alfombra camping']::text[]),
  ('deportes-general', array['pesas', 'mancuernas', 'banco musculacion', 'cinta de correr', 'bicicleta estatica', 'bandas elasticas', 'guantes gym', 'esterilla yoga', 'cinta correr', 'barra dominadas', 'kettlebell', 'rueda abdominal', 'comba crossfit', 'electroestimulador', 'plancha abdominal', 'pelota pilates', 'fitball', 'placas peso', 'guantes gimnasio', 'cinturon lumbar', 'barra pesas', 'eliptica', 'remo indoor', 'saco boxeo']::text[]),
  ('deportes-movilidad', array['patinete', 'bicicleta electrica', 'hoverboard', 'patinete electrico', 'casco patinete', 'candado bicicleta', 'patinete adulto', 'recambios patinete', 'ruedas macizas patinete', 'cargador patinete', 'timbre bici', 'alforjas bici', 'luz bicicleta', 'monopatín', 'longboard', 'patines en linea', 'uniciclo']::text[]),
  ('hogar-bano', array['toalla bano', 'alfombrilla bano', 'dispensador jabon', 'toalla baño', 'alfombrilla baño', 'cortina ducha', 'escobilla wc', 'organizador maquillaje baño', 'espejo aumento baño', 'estanteria ducha', 'jabonera', 'vaso cepillos', 'toallero', 'portarrollos wc', 'alfombra ducha', 'asiento inodoro', 'tapa wc', 'capa baño', 'albornoz', 'esponja baño']::text[]),
  ('hogar-bricolaje', array['taladro', 'destornillador', 'sierra', 'caja herramientas', 'atornillador', 'multitarea', 'lijadora', 'sierra circular', 'pistola termofusible', 'metro laser', 'escalera aluminio', 'amoladora', 'sierra caladora', 'cepillo electrico', 'soldador estaño', 'pistola calor', 'recambio lija', 'brocas taladro', 'sargento carpintero', 'maleta herramientas']::text[]),
  ('hogar-climatizacion', array['aire acondicionado', 'ventilador', 'calefactor', 'radiador', 'deshumidificador', 'humidificador', 'purificador de aire', 'estufa', 'ventilador torre', 'convector', 'calefactor ceramico', 'purificador aire', 'estufa halogeno', 'emisor termico', 'radiador aceite', 'manta electrica', 'almohadilla termica', 'termostato inteligente', 'ionizador aire', 'enfriador aire']::text[]),
  ('hogar-cocina', array['olla', 'sarten', 'cafetera', 'robot cocina', 'air fryer', 'paños de cocina', 'panos de cocina', 'trapo cocina', 'cuchillos cocina', 'bateria de cocina', 'tapa silicona', 'tupper', 'escurridor platos', 'molde reposteria', 'picadora alimentos', 'batidora vaso', 'tostadora', 'exprimidor', 'hervidor agua', 'mandolina cocina', 'rallador', 'tabla cortar', 'especiero', 'papel de horno', 'envasadora vacio', 'botes cocina', 'olla presion', 'sarten antidherente', 'wok']::text[]),
  ('hogar-decoracion', array['cuadro', 'espejo', 'marco fotos', 'vela aromatica', 'florero', 'jarrón', 'figura decorativa', 'planta artificial', 'cojines decorativos', 'portavelas', 'incensario', 'fuentes decorativas', 'centro de mesa', 'vinilo pared', 'letrero decorativo', 'lienzos pared', 'paneles acusticos']::text[]),
  ('hogar-descanso', array['colchon', 'almohada', 'edredon', 'funda nordica', 'sabana', 'topper', 'almohada viscoelastica', 'somier', 'canape abatible', 'protectores de colchon', 'sábanas', 'cabecero cama', 'cojin cervical', 'almohada latex', 'juego sabanas', 'relleno nordico', 'colcha verano', 'base tapizada', 'patas somier', 'funda almohada', 'sobrecolchon']::text[]),
  ('hogar-electrodomesticos', array['lavadora', 'secadora', 'frigorifico', 'microondas', 'lavavajillas', 'horno', 'congelador', 'vitroceramica', 'campana extractora', 'minibar', 'vinoteca', 'frigorifico combi', 'lavadora secadora', 'placa induccion', 'horno empotrable', 'dispensador agua', 'centro planchado', 'plancha ropa']::text[]),
  ('hogar-general', array['cojin', 'cortina', 'alfombra', 'organizador', 'percha', 'cesta almacenaje', 'estores', 'vinilo decorativo', 'reloj pared', 'caja organizadora', 'zapatero tela', 'perchero pared', 'separador cajones', 'fundas sillon', 'placa puerta', 'tope puerta', 'felpudo entrada']::text[]),
  ('hogar-herramientas', array['llave inglesa', 'martillo', 'nivel laser', 'destornillador', 'juego llaves', 'alicates', 'sargento', 'llave carracas', 'maletin herramientas', 'llave vaso', 'cinta metrica', 'destornillador electrico', 'llave allen', 'cortacables', 'prensa terminales', 'arco sierra', 'formon', 'lima metal']::text[]),
  ('hogar-iluminacion', array['lampara', 'bombilla led', 'tira led', 'flexo', 'lampara techo', 'foco led', 'aplique pared', 'lampara mesa', 'plafón led', 'guirnalda luces', 'linterna', 'foco exterior', 'lampara pie', 'bombilla inteligente', 'foco carril', 'luces armario', 'proyector estrellas', 'luz nocturna bebe', 'velas led']::text[]),
  ('hogar-limpieza', array['aspiradora', 'fregona', 'detergente', 'robot aspirador', 'papel higienico', 'papel toilet', 'scottex', 'kleenex', 'bayeta', 'lejia', 'limpiacristales', 'aspirador sin cable', 'mota polvo', 'aspirador mano', 'escoba electrica', 'mopa', 'cubo centrifugo', 'aspirador escoba', 'cepillo vapor', 'pistola vapor', 'recambios robot aspirador', 'mofeta', 'cubo basura', 'papelera cocina', 'escoba y recogedor', 'limpiador suelos']::text[]),
  ('hogar-muebles', array['sofa', 'mesa', 'sillon', 'armario', 'estanteria', 'mesa escritorio', 'silla oficina', 'zapatero', 'comoda', 'mesita noche', 'aparador', 'sillón relax', 'mesa centro', 'mueble tv', 'consola recibidor', 'silla comedor', 'mesa comedor', 'taburete', 'banco almacenamiento', 'estanteria modular', 'libreria', 'escritorio juvenil']::text[]),
  ('hogar-ventilacion', array['ventilador techo', 'ventilador de pie', 'ventilador de mesa', 'ventilador box', 'ventilador usb', 'aspas ventilador', 'ventilador suelo', 'mini ventilador', 'ventilador pinza', 'extractor baño']::text[]),
  ('informatica-general', array['portatil', 'laptop', 'notebook', 'chromebook', 'macbook', 'ordenador sobremesa', 'all in one', 'mini pc', 'portatil gaming', 'torre pc', 'ultrabook', 'ordenador oficina', 'pc custom', 'apple imac', 'mac mini', 'portatil barato', 'portatil 15 pulgadas', 'portatil 17 pulgadas']::text[]),
  ('informatica-perifericos', array['monitor', 'teclado', 'raton', 'ssd', 'tarjeta grafica', 'webcam', 'dock usb', 'memoria ram', 'disco ssd', 'teclado mecanico', 'raton gaming', 'fuente alimentacion', 'placa base', 'procesador cpu', 'alfombrilla raton xl', 'microfono streaming', 'disco duro externo', 'hdd 3.5', 'caja pc', 'ventilador pc', 'disipador cpu', 'pasta termica', 'tarjeta wifi', 'hub usb', 'lector tarjetas', 'switch ethernet', 'router wifi', 'repetidor wifi', 'cable hdmi', 'cable displayport', 'capturadora video']::text[]),
  ('jardin-general', array['barbacoa', 'cortacesped', 'maceta', 'manguera', 'muebles jardin', 'toldo', 'piscina desmontable', 'cortacésped', 'conjunto jardin', 'tumbona', 'manguera riego', 'parasol', 'cesped artificial', 'soplador hojas', 'hidrolimpiadora', 'muebles terraza', 'cojines palet', 'programador riego', 'aspersor', 'tijeras podar', 'cortasetos', 'motosierra bateria', 'motocultor', 'deporadora piscina', 'cloro piscina', 'robot limpiafondos', 'macetero', 'invernadero', 'estufa terraza', 'foco solar jardin', 'cenador jardin']::text[]),
  ('juguetes-general', array['juguete', 'peluche', 'muneca', 'playmobil', 'puzzle', 'coche teledirigido', 'figura de accion', 'lego', 'muñeca', 'juego de mesa', 'puzzles', 'barbie', 'hot wheels', 'nerf', 'drone juguete', 'disfraz infantil', 'cocinita juguete', 'pista coches', 'figura accion', 'bici sin pedales', 'patinete tres ruedas', 'casita juguete', 'plastilina', 'juego educacion', 'monopoly', 'catan', 'carcassonne', 'trivial', 'uno juego cartas']::text[]),
  ('juguetes-manualidades', array['pintura', 'plastilina', 'manualidades', 'lego', 'pistola silicona', 'set pintura', 'acuarelas', 'cartulina', 'laminas para colorear', 'arcilla polimérica', 'rotuladores lettering', 'lienzo', 'caballete pintura', 'pinceles', 'témperas', 'foami goma eva', 'abalorios pulseras', 'lana punto', 'hilo ganchillo', 'papel scrapbooking', 'pistola cola caliente']::text[]),
  ('juguetes-modelismo', array['maqueta para montar', 'pegamento maquetas', 'pintura maquetas', 'aerografo', 'modelismo ferroviario', 'piezas fotograbado', 'maqueta barco', 'maqueta avion', 'maqueta coche escala', 'tamiya', 'revell', 'masilla modelismo', 'cortador styrofoam', 'pincel fino modelismo']::text[]),
  ('mascotas-general', array['pienso', 'arena gatos', 'collar perro', 'correa perro', 'rascador', 'comedero', 'snack perro', 'snack gato', 'transporte mascota', 'piensos perro', 'comida gato', 'arena gato', 'cama perro', 'rascador gato', 'bebedero fuente', 'antiparasitario perro', 'champú perro', 'juguete perro', 'bolsa excrementos', 'pienso gato', 'comida perro', 'collar adiestramiento', 'arnes perro', 'transportin perro', 'bolso transporte gato', 'snacks perro', 'premios gato', 'pecera', 'comida peces', 'jaula hamster', 'lecho gato', 'cepillo pelo perro']::text[]),
  ('moda-bolsos-mujer', array['bandolera', 'bolso', 'bolsos', 'tote bag', 'rinonera', 'mochila mujer', 'cartera mujer', 'bolso mano', 'mochila casual', 'bolso shopper', 'riñonera mujer', 'bolso fiesta', 'bolso saco', 'cartera mano', 'monedero mujer', 'tarjetero mujer', 'bolso hombro', 'neceser mujer']::text[]),
  ('moda-calzado', array['zapatilla', 'bota', 'sandalia', 'zapato', 'zapatillas deportivas', 'botas', 'sandalias', 'zapatos hombre', 'zapatos mujer', 'tacones', 'mocasines', 'botines', 'chancletas', 'zapatillas casa', 'sneakers', 'zapatos oxford', 'zapatos tacon', 'alpargatas', 'zuecos', 'botas agua', 'botas montaña', 'zapatillas running', 'bamba casual']::text[]),
  ('moda-complementos', array['cinturon', 'bufanda', 'gorra', 'guantes', 'gorro', 'guantes piel', 'gafas sol', 'paraguas', 'pañuelo cuello', 'sombrero', 'gorra beisbol', 'cinturon cuero', 'tirantes', 'bragas cuello', 'pasamontañas', 'orejeras invierno', 'fular', 'abanico']::text[]),
  ('moda-equipaje', array['maleta', 'mochila viaje', 'trolley', 'maleta cabina', 'juego maletas', 'bolsa viaje', 'neceser', 'funda maleta', 'mochila portatil viaje', 'candado tsa', 'maleta rigida', 'maleta blanda', 'bolsa deporte', 'carro compra', 'mochila ruedas', 'riñonera viaje', 'organizador maleta']::text[]),
  ('moda-general', array['camisa', 'pantalon', 'chaqueta', 'vestido', 'abrigo', 'sudadera', 'jeans', 'cárdigan', 'blazer', 'falda', 'pijama', 'camiseta manga corta', 'jersey cuello alto', 'trench', 'parka', 'cazadora cuero', 'blusones', 'short vaquero', 'leggings', 'bividi', 'ropa interior hombre', 'ropa interior mujer', 'calcetines', 'medias']::text[]),
  ('moda-joyeria', array['collar', 'pendientes', 'pulsera', 'anillo', 'gargantilla', 'esclava', 'colgante plata', 'joyero', 'anillo compromiso', 'alianza', 'pulsera plata', 'pendientes aro', 'medalla plata', 'broche joya', 'piercing', 'joyero organizador']::text[]),
  ('moda-relojes', array['reloj', 'smartwatch', 'watch pro', 'reloj hombre', 'reloj mujer', 'reloj deportivo', 'reloj pulsera', 'cronografo', 'reloj inteligente', 'reloj automatico', 'reloj cuarzo', 'pulsera actividad', 'smartband', 'correa reloj', 'reloj buceo', 'reloj analogico', 'reloj digital']::text[]),
  ('oficina-general', array['destructora papel', 'calculadora', 'rotuladora', 'silla escritorio oficina', 'pizarra blanca', 'plastificadora', 'contador billetes', 'bandeja documentos', 'silla director', 'lámpara escritorio oficina', 'organizador escritorio', 'cajonera oficina', 'alfombrilla escritorio', 'portanotas', 'sello automatico']::text[]),
  ('oficina-material-escolar', array['mochila escolar', 'cuaderno', 'boligrafo', 'estuche', 'lápices de colores', 'libreta', 'boligrafos', 'compás', 'témperas', 'cuaderno espiral', 'agenda escolar', 'rotuladores', 'ceras colores', 'tijeras infantiles', 'pegamento barra', 'portatodo', 'borrador', 'sacapuntas', 'calculadora escolar', 'carpetas anillas colegio']::text[]),
  ('oficina-papelera', array['impresora', 'ecotank', 'laserjet', 'pixma', 'toner', 'cartucho tinta', 'botellas de tinta', 'multifuncion', 'escaneado', 'epson', 'brother', 'hp officejet', 'canon pixma', 'papel din a4', 'sobres', 'archivador', 'carpeta anillas', 'post-it', 'etiquetas adhesivas', 'taladro papel', 'grapadora', 'papel fotografico', 'cuaderno notas', 'bloc dibujo', 'taladrador', 'grapas', 'clips papel', 'cinta adhesiva', 'corrector liquido', 'marcapaginas']::text[]),
  ('otros-actualidad', array['noticia chollo', 'novedad tecnologia', 'lanzamiento', 'analisis producto']::text[]),
  ('otros-cine', array['blu-ray', 'pelicula 4k', 'dvd pelicula', 'pelicula blu-ray', 'pelicula dvd', 'boxset serie', 'coleccion peliculas', 'trilogia bluray', 'steelbook', 'serie completa dvd', 'pelicula 4k uhd']::text[]),
  ('otros-cupones', array['cupon', 'codigo descuento', 'voucher', 'cupon descuento', 'codigo promocional', 'vale descuento', 'oferta flash']::text[]),
  ('otros-general', array['generico', 'varios', 'articulo', 'producto sorpresa', 'lote ahorro']::text[]),
  ('otros-libros', array['libro', 'kindle', 'ebook', 'tapa blanda', 'libro bolsillo', 'novela', 'bestseller', 'libro ilustrado', 'comic', 'manga', 'biografia', 'libro suspense', 'novela negra', 'thriller', 'libro fantasia', 'libro infantil', 'autoayuda', 'libro cocina', 'diccionario', 'poesia']::text[]),
  ('otros-musica', array['vinilo', 'cd musica', 'tocadiscos', 'disco acetato', 'album musica', 'vinilo edicion limitada', 'cd album', 'recopilatorio musica']::text[]),
  ('otros-supermercado', array['cafe molido', 'aceite oliva', 'pasta alimentaria', 'arroz', 'galletas', 'chocolate tableta', 'infusion', 'te verde', 'pañales', 'panales', 'capsulas cafe', 'chocolate', 'detergente ropa', 'suavizante', 'infusiones', 'pasta dental', 'papel higienico', 'cafe grano', 'te matcha', 'frutos secos', 'snacks', 'bombones', 'vino tinto', 'cerveza', 'refresco', 'leche', 'pasta italiana', 'gel ducha familiar', 'lavavajillas maquina', 'pastillas lavavajillas']::text[]),
  ('otros-viajes', array['maleta cabina', 'hotel', 'maleta viaje', 'mochila antirrobo', 'almohada viaje', 'adaptador enchufe universal', 'báscula maletas', 'funda pasaporte', 'organizador maleta', 'etiqueta maleta', 'tapones oidos viaje', 'antifaz dormir', 'neceser colgante', 'riñonera oculta', 'bolsa impermeable movil', 'cangurera']::text[]),
  ('tecnologia-accesorios-movil', array['funda iphone', 'cargador', 'power bank', 'cristal templado', 'protector pantalla', 'funda movil', 'cargador usb', 'cable tipo c', 'soporte movil', 'bateria externa', 'anillo soporte movil', 'cargador inalambrico', 'cargador coche movil', 'cable lightning', 'cable microusb', 'palos selfie', 'trípode movil', 'lente movil']::text[]),
  ('tecnologia-audio', array['auriculares', 'altavoz', 'barra de sonido', 'airpods', 'soundbar', 'earbuds', 'altavoz bluetooth', 'auriculares inalambricos', 'barra sonido', 'auriculares diadema', 'altavoz inteligente', 'auriculares deportivos', 'cancelacion ruido', 'auriculares bluetooth', 'tws', 'altavoz portatil', 'auriculares gaming', 'radio portatil', 'radio despertador', 'altavoz ducha', 'minicedena', 'subwoofer']::text[]),
  ('tecnologia-electronica', array['tablet', 'tableta', 'ipad', 'android 1', 'android 15', 'android 14', 'kindle paperwhite', 'ebook reader', 'lector de libros', 'gadget', 'electronica consumo', 'multimetro', 'calculadora cientifica', 'traductor simultaneo', 'grabadora voz', 'visor realidad virtual', 'gafas vr', 'puntero laser', 'estacion meteorologica', 'grabadora digital', 'amplificador señal', 'localizador llaves bluetooth']::text[]),
  ('tecnologia-fotografia', array['camara', 'objetivo', 'tripode', 'gopro', 'mirrorless', 'camara fotos', 'objetivo camara', 'trípode', 'camara deportiva', 'flash camara', 'mochila fotografica', 'anillo luz led', 'camara instantanea', 'polaroid', 'instax', 'camara reflex', 'dslr', 'estabilizador gimbal', 'tarjeta sd', 'tarjeta micro sd', 'caja luz fotografia', 'reflector luz', 'control remoto camara']::text[]),
  ('tecnologia-hifi', array['amplificador', 'tocadiscos', 'altavoz hifi', 'receptor av', 'previo fono', 'etapa potencia', 'monitores estudio', 'reproductor cd hifi', 'giradiscos', 'altavoces columna', 'dac audio', 'amplificador auriculares', 'cable hifi', 'plato vinilo']::text[]),
  ('tecnologia-moviles', array['iphone', 'smartphone', 'google pixel', 'pixel 10', 'pixel 9', 'pixel 8', 'pixel 7', 'samsung galaxy', 'galaxy a', 'galaxy s', 'galaxy z', 'xiaomi', 'redmi', 'poco', 'motorola', 'oneplus', 'nothing phone', 'realme', 'honor', 'oppo', 'movil', 'telefono movil', 'movil libre', 'teléfono básico', 'poco phone', 'vivo movil', 'telefono senior', 'movil resistente', 'smartphone 5g', 'celular libre']::text[]),
  ('tecnologia-televisores', array['televisor', 'smart tv', 'oled', 'qled', 'fire tv stick', 'televisor led', 'tv 4k', 'oled tv', 'soporte tv', 'proyector cine', 'pantalla proyeccion', 'tv stick', 'fire tv', 'chromecast', 'xiaomi tv box', 'apple tv', 'television 32', 'television 55', 'television 65', 'qled tv', 'mando distancia tv', 'antena tv']::text[]),
  ('videojuegos-entretenimiento', array['netflix', 'disney', 'tarjeta regalo', 'figura coleccion', 'merchandising', 'funko pop', 'replica oficial', 'poster juego', 'taza friki', 'camiseta gaming', 'lampara 3d led', 'llavero anime', 'figura anime', 'gorra gamer', 'alfombrilla gaming grande', 'poster anime']::text[]),
  ('videojuegos-general', array['playstation', 'ps5', 'xbox', 'nintendo switch', 'dualsense', 'mando xbox', 'steam deck', 'juego ps5', 'juego nintendo switch', 'juego xbox', 'consola', 'mando ps5', 'volante gaming', 'silla gaming', 'tarjeta saldo psn', 'auriculares gaming', 'playstation 5', 'nintendo switch oled', 'xbox series x', 'mando ps4', 'nintendo switch lite', 'asus rog ally', 'juego ps4', 'juego xbox one', 'funda mandos', 'base carga mandos']::text[])
),
resolved as (
  select
    c.id as category_id,
    s.keywords
  from seed s
  join lateral (
    select child.id
    from public.categories child
    join public.categories parent on parent.id = child.parent_id
    where
      lower(child.slug) = lower(s.lookup_slug)
      or (
        lower(child.slug) = 'general'
        and lower(parent.slug) || '-general' = lower(s.lookup_slug)
      )
    order by
      case when lower(child.slug) = lower(s.lookup_slug) then 0 else 1 end
    limit 1
  ) c on true
)
insert into public.category_keywords (category_id, keywords, is_active, notes)
select
  r.category_id,
  r.keywords,
  true,
  'seed:static-inference'
from resolved r
where not exists (
  select 1
  from public.category_keywords existing
  where existing.category_id = r.category_id
);
